#!/bin/bash
# Starts raspberry pi image in in fully functional mode!
 
qemu-system-arm -kernel ./qemu-rpi-kernel/kernel-qemu-3.10.25-wheezy  -cpu arm1176 -m 256 -M versatilepb -no-reboot -serial stdio -append "root=/dev/sda2 panic=1 rootfstype=ext4 rw" -hda 2015-02-16-raspbian-wheezy.img
 -redir tcp:2222:22

