#!/bin/bash
# Starts Debian 9.4.0 amd4 image in in fully functional mode!
# It should be on Host
# sysctl net.ipv4.ip_forward = 1

qemu-system-x86_64 -hda debian-9.4.0-amd64.qcow2 -m 256 -redir tcp:2222::22

